### ISSUE TITLE
Compatibility with dash-to-panel

### ISSUE THREAD

**Issue by ToxicDragon** [aunetx/blur-my-shell#10]
Hi,
@aunetx Thank your for you sweet extension; I really like using it!

However, I came across some bugs that I want to mention.

Extension version: Latest Master branch
System:

Ubuntu 20.10
gnome-shell 3.38.1 @ wayland session
GPU: AMD RX 580 @ amdgpu driver

In order to improve productivity of my gnome-shell experience, I use the dash-to-panel extension as my daily driver (see https://github.com/home-sweet-gnome/dash-to-panel).

I mainly found two problems here:

1. When using your extension in combination with dash-to-panel extension, I way able to only once have the panel blurred aswell. However, when deactivating dash-to-panel, the "default" gnome-shell panel was displayed blurred as it should.

2. The one time I was able to get blur combined with dash-to-panel's panel to work (unfortunately could not reproduce it), the panel was blurred only on my main screen; the panel on the secondary screen did not get blurred.

Could you investigate this behaviour? Maybe this problem also relates to the generell problem of settings that seem to "randomly" only randomly apply once set (see #9 for details). It would be great whether the problem resides in your extension's code or maybe in dash-to-panel's.

Thank you in advance! Keep up the great work!

**Comment by aunetx** [comment]
Thanks for this issue!

I actually do not use dash to panel, so I tested the extension with it only once (and it worked so I let it go), but I will try to test it more wirh it!

I guess I could resolve these two issues as once, as my actual implementation to blur dash to dock is compatible with multi-monitors setup :)

So I will just try to use it too whenever the extension detects dash to panel running, and I will see if it works! If not, I will implement it separately of course :)

**Comment by sertraline** [comment]
To make the blur working you need to load dash-to-panel after this extension, so the step to reproduce would be to enable blur extension and then re-enable dash-to-panel. You also need to have transparency override enabled in dash-to-panel in case you use default adwaita shell theme. With Gnome 3.38.3 I have artifacts flickering over the entire panel.

**Comment by aunetx** [comment]
Thanks @sertraline :)
Doing this, is this extension fully compatible with dash-to-panel? Or do you need to do it every time you log in to gnome?

**Comment by nekohayo** [comment]
Interestingly, once you enable it, if you logout & re-login it works fine, dash-to-panel gets blurred, no matter what order you enabled the extensions in (it may be pure luck though, what guarantees it would be loaded in the correct order on login?)...

**Comment by aunetx** [comment]
I guess the need to logout-login again is not too big, if everything works after that...
@nekohayo did you test this with gnome 40, or older versions?

**Comment by nekohayo** [comment]
I tested only with GNOME 3.38.

That said, I noticed this morning upon resuming from suspend that the dash-to-panel area was not blurred, I had to reload the shell (which I can do with `Alt+F2, R` since I'm on Xorg instead of Wayland) for it work again. So I'll venture a guess that there is a race condition and that, to an extent, the dash-to-panel extension devs should be contacted (summonning @charlesg99 and/or @jderose9) so that _their_ extension interfaces with this extension here when you offer blur "capability" to other apps, as you seem to intend to do with @corvettecole in https://github.com/aunetx/blur-my-shell/issues/31#issuecomment-823642161 (maybe there needs to be a more clearly titled ticket about that, or not).

My worry is that this might be just a case that depends on the order in which extensions are enabled by GNOME Shell, which might vary across computers (if it is indeed a race condition), while yours needs to be first; does GNOME Shell have such a notion of extensions priority ordering/dependencies? Until then, I suspect it might be an unsolvable problem, unless the extensions have a way to communicate with each other with dbus or something.

**Comment by aunetx** [comment]
I looked at their code, and found the exact line where my extension seems to break... The problem is that they can't really do anything about it (as they replace the existing dock, so they replace everything my extension connected to)

I guess the best way to patch this problem would be for them to emit a signal at the moment where hey replace the dock, so that I can catch this signal and re-enable the blur then.

**Comment by CorvetteCole** [comment]
@nekohayo You can track the integration of blur-provider in #39 . I have actually been contributing to the Gnome 40 port of dash to panel, so I may do the legwork with integrating blur on their side as well. I have a lot of work to do before then however, and I'm still open to other solutions

**Comment by CorvetteCole** [comment]
@aunetx if you still have the line where your extension breaks it would be good to put that here so I can take a look at it later and potentially fix it

**Comment by aunetx** [comment]
Well, this is https://github.com/home-sweet-gnome/dash-to-panel/blob/master/extension.js#L115
At this moment, the best thing would be to receive a signal so that Blur my Shell can reload the panel blur (as it seems to work well if the extension is activated after Dash to Panel)

**Comment by CorvetteCole** [comment]
hey @aunetx take a look at this: https://github.com/home-sweet-gnome/dash-to-panel/blob/e4a71fa014b565171c93d15f436be9c3599b11fb/extension.js#L54.

It seems they have code to specifically handle if the Ubuntu dock extension is enabled after it (a signal). Sounds like we could do the same thing and reload our changes when that happens.

I attempted to implement this idea in #41 . I described the problems with that approach in there, but it may be solvable.

We may need to create some custom component similar to dash to dock to handle dash to panel, not sure. You are the expert here! 

Also, I would like to have repo write access when you have a chance. I am going to organize all my code with branches and pull requests, but want to be able to mark the pull requests as related to issues etc for better organization. I will always have you be the one to merge in to master from a branch.

**Comment by aunetx** [comment]
Thanks a lot for this, you're really doing great job! And I'm still stuck with preferences haha

If this change works, I don't think we will need to add another component! I added one for dash-to-dock because it works very differently (as you can see by the mess in my extension), but dash-to-panel works by itself from what I understood :)

And of course I will give you write access right now, this will be easier to work I imagine!
And don't worry, you can merge and commit to master (I think that the important thing is not to commit to master very wip things if they are big changes, like you do for #39, but for small changes it is ok) :)

**Comment by aunetx** [comment]
@CorvetteCole I added you as collaborator, I don't know if github wants me to do others changes or if you directly have the rights you need!

**Comment by CorvetteCole** [comment]
I am a little crazy about organizing my code in general, so I'll make my commits in separate branches then merge when tested and ready no worries. Also, yes I got the request and I am a collaborator now! Excited to make this the blur I set out to create when I made blur-provider.

**Comment by CorvetteCole** [comment]
The current master branch should support dash to panel, although you will need to manually make it transparent in the dash to panel settings. This only applied to Gnome versions >= 40.0

**Comment by CorvetteCole** [comment]
there are a few more related issues that need to be fixed for full compatibility but I will track them in #49

**Comment by aunetx** [comment]
@CorvetteCole thanks a lot for all your work, and sorry for taking a lot of time to answer :)

**Comment by CorvetteCole** [comment]
No problem we are all busy people!
