### ISSUE TITLE
opaque bar around the dock, even with GTK4 themes

### ISSUE THREAD

**Issue by Araly** [aunetx/blur-my-shell#131]
Hey, I'm the author of this issue that was solved a while ago: #89 We had "solved" the issue by using an up to date theme.

I'm having pretty much the exact same issue as before, except that this time the themes are GTK4, and even the issue even appears on the default manjaro GTK theme "matcha-dark-sea"

![extension disabled](https://user-images.githubusercontent.com/24990801/134429283-7da2b848-fc52-45a5-b5ce-ca2d313aa631.png)
![opaque bar](https://user-images.githubusercontent.com/24990801/134429285-4a7ef338-8625-4068-8589-34c7bbdaffdb.png)

You'll also see that when I disable the extension, there's still the same opaque bar instead of the grey background, so maybe the issue comes from some other place than this extension ?

**Comment by aunetx** [comment]
Thanks for the report, I see the issue... Does this happen with default gnome theme (adwaita/adwaita dark)?

The problem is that I could force the opaque bar to be transparent, but I'm worried it might limit the possibilities of customizations after that... (even though it really is secondary, as this definitively looks broken now anyway).

**Comment by Araly** [comment]
I didn't test it with adwaita, but I had tested it with the matcha theme. I've since hopped to endeavourOS, installed Gnome and blur-my-shell, and everything works well. So I guess we can close this for me not going to be able to reproduce it again. Maybe it will come back and I can open it again then, or if someone has the same issue they can open it again.
