### ISSUE TITLE
No animation when disabling overview

### ISSUE THREAD

**Issue by Fushko** [aunetx/blur-my-shell#15]
There is no animation when going out of the overview, even though "animate overview" is checked.

**Comment by aunetx** [comment]
Thanks for the report, I am aware of this (but forgot to tell it): this is due to a bug in gnome shell regarding overview's background opacity, so my current (and pretty simple) implementation of animation is totally broken.

The bug is that, when opacity is augmented (to enter overview), the animation is pretty fluid. However, if you want to lower the opacity, it is not updated for a lot of frames, so it is horribly ugly.

I chose to just not animate when going out of overview so it is at least fluid, but I will change this if I ever find a way

**Comment by aunetx** [comment]
Thanks to @yozoon, animation is there and without any problem now!
