### ISSUE TITLE
Feature Request: Optional Unblur Dash/Dash-to-Dock in Overview

### ISSUE THREAD

**Issue by maxlahn** [aunetx/blur-my-shell#193]
It looks like the dash (or dash to dock) gets double the blur effect in the overview if both Dash and Overview are selected to be blurred. This results in a net difference in brightness and sigma for the dash as compared with the top panel.

In some configurations of dash to dock (namely panel mode on the left- or right-hand side, this results in some weird behavior (see the top left corner of the first image attachment):

![Screenshot from 2022-02-24 19-39-45](https://user-images.githubusercontent.com/98011559/155631628-372b546c-e205-4cd1-a4b1-213e368ab9b7.png)

If I disable dash blur, this issue is resolved (see the second image attachment):

![Screenshot from 2022-02-24 19-40-51](https://user-images.githubusercontent.com/98011559/155631643-3fb45b0c-8b2f-4523-9f61-25e179fdccf6.png)

Is it possible to add an option to blur the dash except in the overview? In any case, thanks for a great extension!

**Comment by maxlahn** [comment]
> what you should do is have a nice GNOME theme that is styled nicely, I'm working on that, this is why I think the blurred areas should not be darkened in most cases

I've been using the default theming, but if you end up creating one that solves this issue, please let me know :)

**Comment by andrewaclear** [comment]
For sure, I'm working on it. It's a lot of work to get the theme all clean and not buggy.

**Comment by aunetx** [comment]
Sorry for not answering before, yes I will provide this as an option, hopefully for gnome 42! And if I don't have the time to finish this, this will be done at one point anyway, sorry it it takes some time...

@andrewaclear the problem here is that even if dash-to-dock is not darkened, it will still be blurred on top of the overview, which is enough to make it look ugly (especially if the sigma is low).

By the way, I think (if I remember correctly) the default behaviour should be that dash-to-dock blur is disabled when entering overview, so it may be a bug -- but providing an option is necessary anyway here.

**Comment by maxlahn** [comment]
Thank you so much!

**Comment by andrewaclear** [comment]
@aunetx I know what you are saying but if it's styled correctly (a good theme definitely makes a big difference) it should be way better if it is still blurred in the overview. For example see mine here https://github.com/aunetx/blur-my-shell/issues/195#issuecomment-1058236088. The main reason being when multi-touch scrolling down to the app menu. It would look bad if there wasn't a blur behind the dock as the apps pass under it.

**Comment by aunetx** [comment]
I agree with you, but the current problem is that it is not possible to have rounded corners for the dash, so it is squared and that's not what most users want. Disabling the blur entirely in overview makes one able to have clean rounded corners, using a simple transparency, as the background behind is already blurred (except... when opening app grid, yeah).

Others problems are that dynamic blur is slower than the blur user in overview, so it degrades performance for little to no addition; and that double-blurring the dash (once for the overview, and then again with the dash blur) is not wanted at all -- there is no control anymore about the amount of blur wanted, so except if I have a way to blur only once (as I did for the panel, which allows you to change the sigma without problem), the default should probably not be to lower the brightness dynamically without changing the sigma.

**Comment by andrewaclear** [comment]
@aunetx i see what you are saying. The corners should be rounded 100%, but I treating my development as if we can round corners to be ready for when we can, and tbh I actually think it looks a lot better to at least have a blur with the corners then to not have it at all. Additionally, darkening the blur background is what actually makes the corners look worse because they are darker. If we just use the theme for the elements and leave the blur fully bright the corners are less visible. I understand that blurring the dock on top of the overview is not ideal, but I think it is the only way because when scrolling down to the apps, seeing them clearly under the transparent dock is not good at all.

**Comment by aunetx** [comment]
This is fixed in #180! You can try it already if you have gnome 42 @maxlahn 

However, this is not a clean fix, as Dash to Dock is much harder to blur than anything else, so the blur might not be disabled at the exact right time when entering/leaving the overview -- however it should be good enough, I guess

**Comment by aunetx** [comment]
> @aunetx i see what you are saying. The corners should be rounded 100%, but I'm treating my development as if we can round corners to be ready for when we can, and tbh I actually think it looks a lot better to at least have a blur with the corners then to not have it at all. Additionally, darkening the blur background is what actually makes the corners look worse because they are darker. If we just use the theme for the elements and leave the blur fully bright the corners are less visible. I understand that blurring the dock on top of the overview is not ideal, but I think it is the only way because when scrolling down to the apps, seeing them clearly under the transparent dock is not good at all.

Yes, I understand your point of view. However I can't really develop as if it was possible to blur the corners, because it implies a lot of changes in this extension, and there is no sign of any change in the gnome team about this issue (which is not an actual issue for them, as they do not use the blur effect in gnome-shell itself in this way).
The new preferences allow you to change the brightness however, so this could be god enough for the moment for the users who want it to add the corners themselves from css!

**Comment by maxlahn** [comment]
> This is fixed in #180! You can try it already if you have gnome 42 @maxlahn
> 
> However, this is not a clean fix, as Dash to Dock is much harder to blur than anything else, so the blur might not be disabled at the exact right time when entering/leaving the overview -- however it should be good enough, I guess

Thanks so much! I'm looking forward to trying it out when I update to 42 :)
