### ISSUE TITLE
Blur darkness, backgrounds, and sigma

### ISSUE THREAD

**Issue by andrewaclear** [aunetx/blur-my-shell#195]
I think there needs to be a change in the way blurred is used. 

1. Each object should not have the same **sigma**.
    - overview and login screen should be blurred more
    - dash to dock, panel, applications, folders, ... should be blurred less
2. Each object should not have the same blur **brightness**.
    - overview and login screen should be a little darker
    - dash to dock, panel, applications, folders, ... should not be darker at all, their backgrounds should be determined by the GNOME theme
3. The **backgrounds** of objects should not be removed and replaced. I understand that you are trying to make this extension work with the default GNOME theme which doesn't have the transparency that you need but this is not the right way. I am working on a theme that has a transparent version which is properly styled such that the extension should only add a blur background to the objects without any added darkness or change in the elements.

**Comment by andrewaclear** [comment]
This would solve this issue https://github.com/aunetx/blur-my-shell/issues/193#issue-1149918149

**Comment by aunetx** [comment]
Hello, and thanks for the ideas!

To be honest, most of this is already done in pull request #180: it allows you to change each component's blur preferences, so that you can blur what you want, the way you want.

It is not finished yet, but everything is working -- preferences just need to be changed through gsettings, as I explained in the comments. 

I still have not implemented the option to enable/disable the background for each component, but I intend to do so. However, I will continue to make this possible without changing the theme, because I don't want everybody who wants to blur its panel having to use some specific theme. You option of creating a transparent theme is of course better though, and should be preferred when possible.

I also think the default settings should be to have the same blur/brightness value for every component when the extension is first installed, because it gives an interface way cleaner: having the panel blend into the overview is the default behaviour of gnome, so I think it should not be changed.
For dash-to-dock... It's an harder question, for a lot of reason, related both to the implementation and the look the dash have when in overview. 
I will provide options anyway, and I hope I will finish the preferences gui before gnome 42!

**Comment by andrewaclear** [comment]
Oh that's great about the pull request. Awesome thanks! Ya it would be fair to leave the option to remove the background for people that want to use other themes that don't have transparent objects. I guess about the blurring of the panel and dash it depends on the style of the theme. Like if it's done right I think it looks good (like in mine above, they have different sigmas than the overview). Also, like what I mentioned here https://github.com/aunetx/blur-my-shell/issues/193#issuecomment-1058937687 about scrolling over the apps, the dash should be blurred in the overview. 

You could make the settings all the same as the default, but it does leave the user to do work to set it up. I think it might be better to have an optimized look as the default and I think bigger areas should be blurred more than smaller areas aesthetically, and like I said, I think darkening the overview background and Lock Screen is better to add depth, and not darkening anything else. But this is just what I'm thinking from my eye idk.

**Comment by aunetx** [comment]
@andrewaclear you can install from the PR #180 if you have gnome 42 already, this adds the possibility to have different blur prefs for the components from the preferences.

By default, there is still the same preferences as it allows for a much more unified look, and I did not tried to fix the background issue -- I may focus on this at some point, but I really don't want to force any user to install another theme in order to correctly use this extension

**Comment by andrewaclear** [comment]
sounds good, thanks! I know what you mean about the theme too, for sure makes sense, I agree.

**Comment by aunetx** [comment]
I close this at this should be fixed now!

**Comment by andrewaclear** [comment]
Awesome. Thanks

**Comment by andrewaclear** [comment]
Awesome. Thanks
