### ISSUE TITLE
Top panel gtk backgroud

### ISSUE THREAD

**Issue by andrewaclear** [aunetx/blur-my-shell#22]
Instead of just overriding background of the top panel I was wondering if you could leave the gtk background and add the blur behind it as you did for the dash, so then like I could set the transparency directly in the gtk css and then we could also have a shadow behind it which would be sweet.

**Comment by andrewaclear** [comment]
This may mean that some people that use the default gnome black top bar won't see any blur behind the bar, but they should most likely use a different theme.

**Comment by TecCheck** [comment]
Maybe you could add an option to make the top panel background transparent. Then you don't need to override the panel background and people with other themes could still see the blur.

**Comment by andrewaclear** [comment]
Ya but it's fine because I could just do it in the CSS theme file. Like WhiteSur would be pretty good already. I would like some modifications myself though.

**Comment by aunetx** [comment]
Sorry for the late reply!

I will see what I can do, and if I have the time I will of course add an option to tweak this :)

I prefer at least having an option (enabled by default), because letting the user add top panel transparency by himself is not very clear (and tweaking css files really is a burden, especially when they are updated...)

**Comment by aunetx** [comment]
The extension now use plain CSS to change top panel background, and it will be very hard to do it another way due to how gnome changes the top panel opacity after every overview showing/hiding...
Changing the CSS is now easier (as it will require simply changing the stylesheet.css file), but I can't really do more without adding a lot of complexity to the extension.

I will close this issue, but feel free to reopen it if it is still not convenient at all
