### ISSUE TITLE
Installed and not working

### ISSUE THREAD

**Issue by DanMeadWasTaken** [aunetx/blur-my-shell#259]
Arcolinux, gnome 42.1, blur my shell 42-37

Error code: Main.overview._overview is undefined

**Comment by aunetx** [comment]
That's really unexpected, do you use other extensions?

**Comment by DanMeadWasTaken** [comment]
Honestly, it'd seem a handful of the extensions i'm installing that i was using on Manjaro are having the same or similar issue.
Mostly i'm just using the preinstalled ones but as i am writing i am using:
Awesome Tiles
Blur my Shell
Dash to Dock for COSMIC (because for some reason normal dash to dock has a weird graphical issue on ArcoLinux)
Gnome 4x UI Improvements (has a similiar issue)
Gnome clipboard
just perfection (has a similiar issue)
Messaging Menu
Tweaks & Extensions in System Menu
VirtualBox applet
VPN Toggler
Yakuake
Then the rest are the built in ones- specifically ones that seem to come prebuilt with all, not including ones that manjaro also adds

**Comment by strykenKN** [comment]
the same for me. Blur simply does not work and under Wayland already twice not. I have exactly the same problems as @DanMeadWasTaken under Fedora 36, but Blur my Shell has never worked under Wayland, you can do what you want. I also don't understand why, Wayland is not supported here, Xorg is old and hardly anyone uses it anymore.

**Comment by aunetx** [comment]
@strykenKN mind you, Blur my Shell works for me, under both wayland and xorg -- so the problem is not just that it never supported it...

The thing here is that blur my shell expects GNOME shell to well, have an overview; and the overview does not seem to exist or at least to be accessible by the extension.

This could be caused by another extension that removes it, but I don't see which one could cause any problem here; or else I don't know how this could possibly happen... Do you have any particularity in your setup?

**Comment by DanMeadWasTaken** [comment]
Before i close this- I'd like to say, I've learned a lot since then, and despite the amount of time elapsed... i believe it was literally that i was unknowingly using gnome classic.
