### ISSUE TITLE
Applications Blur: "Plank" causes a blurred bar across entire screen, Lingering blurred window on Close

### ISSUE THREAD

**Issue by taconomix** [aunetx/blur-my-shell#310]
Hello, 

If this is a duplicate please delete. When the "Applications Blur" is active, my dock "plank" causes a blurred bar across the entire screen. Also the blur lingers for about 1 second whenever an application is closed. This issue hasn't come up before this week, I'm not sure if Applications Blur was only activated on the most recent GNOME update (42.4) or if it just wasn't an issue on the previous version. I've attached a screen recording so you can see what I mean. OS is Arch; Kernel is 5.19.2; Extension added from the AUR (package `gnome-shell-extension-blur-my-shell`).

This isn't a priority issue or anything, I just disabled the Applications Blur. Just thought I'd send it so you were aware. Thanks for this extension by the way. Makes GNOME look SO much better. Cheers. 

https://user-images.githubusercontent.com/69542501/185751101-da4dee85-6c9f-4655-807a-27c12b4e59e7.mp4

**Comment by aunetx** [comment]
Hello and thank you for opening this issue.

Unfortunately, there is not much I can do about it, in the sense that some applications (and widgets like plank) will not work well with the blur.

The only sensible thing I could do is adding Plank by default to the blacklisting, this way new users will have Plank already blacklisted and won't need to add it themselves. Would it sound right to you?

If I do this, I will open an issue to list applications (by its wm-class) that should not be blurred by default, in order to add them to the blacklist; so everybody can add the ones that notoriously won't work.

**Comment by taconomix** [comment]
Yeah, I think blacklisting Plank by default is a good move. It was kind of a leap that I realized the issue was from blur-my-shell, at first I thought Plank was just acting weird.  I think the applications list to not blur by default is a good idea, if it isn't too much trouble. Since it is easy to add to the blacklist, and the Application Blur menu does say clearly that the Application Blurring is in beta and may act weird, I wouldn't make it a high priority. Thank you for the response!

**Comment by YaQia** [comment]
omg, I guess I have understanded why my plank changes into "transparent mode" : none of the icons are visible. I just downgraded blur my shell, and everything works fine now.
