### ISSUE TITLE
Flickering after opening another terminal. 

### ISSUE THREAD

**Issue by kinguardo** [aunetx/blur-my-shell#328]
Blur works well when one terminal is open, but as soon as I open another one then the artifacts appear. This seems to only happen whenever the second instance of a terminal is started. I am using urxvt.

https://user-images.githubusercontent.com/45787099/186994649-4bee222d-1bbd-4bb9-9b57-a92cc61d0323.mov

**Comment by aunetx** [comment]
Thank you for opening this issue. There is definitively something wrong with the way I manage the blur to get it like this, however this is mostly an issue from gnome-shell itself.

In next update (very soon), you will have the option to permanently remove artefacts, which is very useful when using application blur like you do. You can test it right now by installing the extension from here, and changing the hacks level to "no artefact" in the preferences.

**Comment by kinguardo** [comment]
I can confirm compiling the code manually and ticking the "no artifact" setting fixed the issue. It works really well and no artifacts are visible at all. :+1: 

Last piece of the puzzle is rounded corners, you could see in my video that rectangles are sticking out on the edges of my terminal window. This is related to [185](https://github.com/aunetx/blur-my-shell/issues/185) and [265](https://github.com/aunetx/blur-my-shell/pull/265) correct? 

In my case, wouldn't just adding a small margin at the top fix the issue? So the top side of the rectangle wouldn't overlap with rounded rectangle.

**Comment by aunetx** [comment]
Thank you for testing this, I'm glad that it's working well!

For the rounded corners, there is nothing I can do for the moment. However, as you said it, adding a small margin at the top would entirely fix the issue in your case, because the application handle is opaque (which is not the case if the transparency is applied from the extension).

In the future (but not right now), I will add per-application options, which will permit to
- change the blur preferences
- change the transparency
- add margins

If you want to fix it in your case (but this will be applied to every window, so only truly transparent ones will be correctly blurred), you can try to tweak the function `compute_offset` in `src/components/applications.js`, for example with

```js
return {
            x: frame.x - buffer.x,
            y: frame.y - buffer.y - 15,
            width: frame.width - buffer.width,
            height: frame.height - buffer.height - 15
        };
```

(I did not try it, and maybe 15 is too much / not enough, but something like that may work)

**Comment by kinguardo** [comment]
This worked perfectly for me

```js
return {
    x: frame.x - buffer.x,
    y: frame.y - buffer.y + 10,
    width: frame.width - buffer.width,
    height: frame.height - buffer.height - 10
};

```

![image](https://user-images.githubusercontent.com/45787099/187048045-874281d5-9458-4d6a-ab88-51376dadbbe3.png)

While the setting of margin functionality is yet to be implemented, this thread should be useful for anyone who has the same case as me :+1:

**Comment by aunetx** [comment]
I'm glad it worked then!

This could be useful effectively, I may post this in the readme later :)

PS: your allacritty is probably the first time an application is fully and properly blurred with gnome-shell ever, with no artefacts AND no straight corners when they should be rounded!!
