### ISSUE TITLE
Application Blur, issue w/ conky

### ISSUE THREAD

**Issue by Paulie420** [aunetx/blur-my-shell#334]
I *think* I've tracked this issue to 'application blur'. When its toggled on, my conky info (window?) is hidden/blurred... so I thought OK, add it to the whitelist - but since its hidden/blurred, I can't easily select the window. I tried just typing in 'cocky' as the class, but this isn't right.

Am I correct that Application Blur will hide Conky? Is there a way to whitelist it, can I find its 'class name' manually? And/or, is there a way blur-my-shell can use this info to make it just work?

Thanks - love the extension.

**Comment by aunetx** [comment]
Hello, I just added Conky by default in application blur blacklist (used when you use "enable all"), in last commit (you either need to wait for me to upload it, or install it from github).

In order to use it, you may need to reset your preferences using the button in general preferences; as Conky seems to complicate a little bit how selecting applications work... Or you can add "Conky" in blacklist using dconf, in blur-my-shell settings (first option is easier, second one does not require you to reconfigure blur-my-shell).

I close this issue, however if is still appear (as I only tested conky quite fast), you can re-open it without problem!
