### ISSUE TITLE
Feature Request - Light/Dark mode or settings profile saving

### ISSUE THREAD

**Issue by seanleavy** [aunetx/blur-my-shell#344]
Hi great work with all of this. Have a request

Allow a Dark/Light blur profile setting to match Gnome's `org.freedesktop.appearance.color-scheme` setting. 

Use case:
Currently there are instances where the blur settings work well with a light shell theme or a dark shell theme, but not both. 

Eg:
Current blur settings tailored to a light shell theme (OK):
![Screenshot from 2022-09-15 16-37-10](https://user-images.githubusercontent.com/2906363/190447064-c35c38f2-51d1-47cc-80f1-0b0b1e73d8b9.png)

Same blur settings with dark default shell theme. 
![Screenshot from 2022-09-15 16-37-47](https://user-images.githubusercontent.com/2906363/190447231-237f92eb-87a3-41cd-b396-aa79845737b8.png)

I usually go into the **blur my shell** settings to manually adjust the brightness & colour settings when swapping between dark & light apperance.

Was wondering if having a separate dark & light profile setting that syncs with `org.freedesktop.appearance.color-scheme` would be feasible?

**Comment by aunetx** [comment]
Hello, to be honest I won't add something like this due to the enormous complexity it would add to the extension.

However, you can use [Night theme switcher](https://extensions.gnome.org/extension/2236/night-theme-switcher/) run commands when the night time is activated for example, and then change the preferences of blur-my-shell to what you want.

To change the sigma, for example:

```sh
gsettings set org.gnome.shell.extensions.blur-my-shell sigma 100
```

And you can use dconf (or directly gsettings) to know the keys you want to change.

**Comment by seanleavy** [comment]
Sure np. Can close this one

Thanks for the command tip too

**Comment by seanleavy** [comment]
Just want to add if anyone wants go the command route; You will have to add the extension path to its' schema in order to use gsettings

Eg:

`gsettings --schemadir ~/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/schemas/ set org.gnome.shell.extensions.blur-my-shell sigma 100`
