### ISSUE TITLE
settings panel

### ISSUE THREAD

**Issue by icedman** [aunetx/blur-my-shell#361]
Very nice extension - my overview is so much better.
Settings panel look very nice too. wow libadwaita. But is this the reason the extension works only from 42?

Also permission to "borrow" some of your conveniences code for my own extension :)

**Comment by aunetx** [comment]
Hello, thanks for the compliments :)

Yeah, the new versions are incompatible with gnome 41 and older because of libadwaita in the prefs; I think you can make everything compatible by using two preferences for gnome 41 and older (using gtk) and for later version with the current libadwaita prefs, however this would require more maintenance so I choose not to do this.

And of course, feel free to use whatever works for you!
