### ISSUE TITLE
feature-request: Add GNOME 44 support

### ISSUE THREAD

**Issue by git-Hmmm** [aunetx/blur-my-shell#404]
### Describe the idea or feature you'd like
It would be beneficial to have this extension be functional in gnome 44 as the beta phase has already begun.

### Is your feature request related to a problem? Please describe.
nope

### Additional context
nope

**Comment by aunetx** [comment]
Hello, have you tested the extension under GNOME 44? I don't want to add the version number too quickly if it has problems, but if everything works well I will of course update it very soon!

**Comment by git-Hmmm** [comment]
I am confident that the top bar blur and overview blur are working correctly, however, I am unsure of the other elements.

**Comment by carlwgeorge** [comment]
I loaded up the extension (`/org/gnome/shell/disable-extension-version-validation` set to true) in a Fedora 38 nightly image with GNOME 44 beta, and it appears to work fine.

**Comment by lakotamm** [comment]
I found this issue with workspace thumbnail blurring:
https://github.com/aunetx/blur-my-shell/issues/415

**Comment by cassop** [comment]
I don't know if you noticed it, but it will interfere with [pin on top](https://extensions.gnome.org/extension/4691/pip-on-top/) extension and [conky](https://github.com/brndnmtthws/conky), I have checked it multiple time and reporoduced it with new account.

for `conky`,  it open and works as expect but once if you switch to another workspace for some reason the conky will be lost from the screen and turning the extension (blur my shell) off will bring back the conky screen/window.

similar thing happens with `pin on top` if `show on all workspaces` is `on`, lets say a video is on pip mod in ff and if you switch to other workspace the video will be lost but you can see it in the activities overview, and turning the extension off will bring expected behaviour.

**Comment by aunetx** [comment]
Hello, I will push the update right now.
