### ISSUE TITLE
Extension affects lock screen even if the handling of lock screen is disabled on its preferences

### ISSUE THREAD

**Issue by pacho2** [aunetx/blur-my-shell#452]
I am trying to make this extension and https://github.com/neffo/bing-wallpaper-gnome-extension to behave properly together, because that one is the only one properly disabling the blur in lock screen also after resuming from suspend (after applying https://github.com/neffo/bing-wallpaper-gnome-extension/issues/113#issuecomment-14022271699. I look for setting no blurring at all with bing extension while using blur-my-shell for other components.

But even if I have extension handling of lock screen disabled:
![image](https://github.com/aunetx/blur-my-shell/assets/923400/243bd7c8-ad23-4ece-bbfc-1dda1a461f03)

It still seems to change the blur of the lock screen from time to time, usually when resuming from suspend and also showing something like observed in https://github.com/aunetx/blur-my-shell/issues/384 : the top panel gets a different blur in the lock screen even if, supposedly, I have configured the extension to not play with it :/

I wonder about why disabling the option in the setting doesn't completely prevent blur-my-shell extension from playing with the blur settings sometimes :/

Thanks a lot

**Comment by aunetx** [comment]
Hello, the top panel is entirely controlled by the panel settings, and the lockscreen blur only affects the background... And unfortunately, due to #384 (which would require some changes in the way the extension is loaded by gnome shell, so that it is used in lockscreen), I can't get to simply disable the panel blur in lockscreen :/

So closing this in favour of #384 :)
