### ISSUE TITLE
The top bar has low contrast in GNOME 45's light style.

### ISSUE THREAD

**Issue by vixalien** [aunetx/blur-my-shell#481]
GNOME 45 introduced a light-style feature that sets the shell style to light mode. However, when used in conjunction with blur my shell, the text is black which causes some contrast issues.

![image](https://github.com/aunetx/blur-my-shell/assets/37999241/e54e00a2-cd25-424a-8ca0-ee270116ddc0)

The top bar text changes color to white immediately when I do the overview gesture.

![image](https://github.com/aunetx/blur-my-shell/assets/37999241/d36f8973-a4a1-4a43-aee8-4ad80990f2bf)

**Comment by IdkWhatToCallMe123** [comment]
poor battery...

**Comment by aunetx** [comment]
I just forced myself to use the light theme so I am forced to fix this :D I will probably add a chooser in panel preferences between:
- use light text color (default) 
- use dark theme color
- automatic, which does nothing as it would follow the shell theme behaviour

The problem is that some extensions do not seem to use the text color for their text/icons (from what I saw, appindicator always uses white icons, and the netspeed extension I use follow the shell theme but do not change its font color between overview/not overview). But that's only related issues so I will see what I can do

**Comment by aunetx** [comment]
I am adding this, but I will finally just provide a switch: either force the use of light text, or use the default colour provided by the theme. For other behaviour (which are less common), the user should really customize its theme himself, as it is not really up to blur-my-shell to tweak it :)

**Comment by aunetx** [comment]
I fixed this in last commits, this will be added to the next release. There is now an option in preferences to force using light text, and you can enable it all the time as well because it does not affect the shell when using dark theme :)
