### ISSUE TITLE
Panel Blur Uses Wrong Wallpaper (Multi-monitor)

### ISSUE THREAD

**Issue by pixlxip** [aunetx/blur-my-shell#486]
I use different wallpapers for each of my 2 monitors on GNOME 45, but Blur my Shell seems to choose the wrong wallpaper for the panel blur. Restarting the extension from Extensions or Extension Manager fixes it, but the problem persists on startup.

Here's an image:
![image](https://github.com/aunetx/blur-my-shell/assets/99521063/96d48f49-cc63-4b12-b9dd-3a2fd647d1ba)

It might be relevant that I use my right monitor as my main one.

**Comment by aunetx** [comment]
Hello, could you try PR #546 to see if it still happens? It should not, as I now use the default GNOME class to fetch the wallpaper! So I set this issue to be closed automatically once #546 is merged, however please tell me / reopen it if it still appears

**Comment by Cardidi** [comment]
I believe this issue is not fixed yet. I produce this bug on Ubuntu 24.04 under X11 with 2 monitor connected. One is rotated to vertical, another one is horizental. Almost everytime my PC power on and first login to desktop, my top panel will showing like this:

![image](https://github.com/aunetx/blur-my-shell/assets/26651344/5868644b-e90c-4673-b7f3-cd82553d2db4)
