### ISSUE TITLE
Dash to Panel transparency not respected

### ISSUE THREAD

**Issue by CorvetteCole** [aunetx/blur-my-shell#49]
The transparency settings of dash to panel should be either modified or not. Currently dash to panel needs to be manually set to transparent for blur to be seen, and when panel blur is disabled in blur-my-shell, it gets set to the original color regardless of if transparency is enable in dash to panel or not. This needs to be fixed eventually (low priority)

**Comment by CorvetteCole** [comment]
As mentioned in #10 , "The one time I was able to get blur combined with dash-to-panel's panel to work (unfortunately could not reproduce it), the panel was blurred only on my main screen; the panel on the secondary screen did not get blurred."

This is still a problem for now.

**Comment by aunetx** [comment]
Yeah, that's effectively something that must be fixed :)
Do you think we should have to set the opacity in dash to panel, or that blur my shell should do it automatically?

**Comment by CorvetteCole** [comment]
I personally feel like we should just apply the blur, and require the user to apply opacity in dash to panel settings. That way users could combine that with the dynamic panel transparency and stuff without any work on our side. I think we need a way to detect dash to panel on first startup as well, not just when it is enabled. So we can apply some specific changes

**Comment by aunetx** [comment]
I personally would like to wait for dash-to-panel and dash-to-dock to be stable for gnome 40 before doing this, as there was (last time I tested) no way to change opacity for dash-to-dock (settings did not work correctly), and removing transparency for dash-to-panel should mean doing the same for dash-to-dock...

Except if we let the user choose it directly with the slider inside the extension preferences, which would be easy to implement (although we would need to verify each time if the panel is used by dash-to-panel or not, because else sliding the cursor would mean changing panel opacity too...

**Comment by aunetx** [comment]
This seems to be fixed now, with latest commits I pushed :)
I will also try to get the exact same behaviour for dash-to-dock, as soon as it is officially released for gnome 40.

Closing this, feels free to reopen it if anything is wrong.
