### ISSUE TITLE
[Feature Request] Blur Nautilus sidebar in Gnome 45

### ISSUE THREAD

**Issue by ryanfelder** [aunetx/blur-my-shell#490]
Since I don't expect the Gnome developers to ever agree to doing this, I think it would be a gorgeous upgrade to nautilus if I could set a blur effect on just the sidebar of Nautilus in Gnome 45.

An example of what this might look like can be seen on this twitter thread about GTK on MacOS

https://twitter.com/paulrouget2/status/1595357518913449992

![Screenshot from 2023-11-08 10-41-27](https://github.com/aunetx/blur-my-shell/assets/7475484/1f02cdd8-b0a4-49aa-bfc0-73d36c07dad9)
![Screenshot from 2023-11-08 10-41-46](https://github.com/aunetx/blur-my-shell/assets/7475484/27b2255e-0ab3-436c-88ce-05530163b1f9)

**Comment by ryanfelder** [comment]
Or maybe just every usage of the new gtk sidebar. No idea if that's possible.

**Comment by aunetx** [comment]
Hello, that would be awesome, however that's not doable from the extension (see #472). This would really require changes in the GNOME stack (gtk4, mutter, gnome-shell, and probably other) so that is up to the official project :)

I guess that would be possible if someone wanted to try and patch gtk4/mutter (probably in the same vein as https://github.com/yilozt/mutter-rounded), but that out of scope for this extension (and I don't have the manpower to do something like this, as you can see with the number of opened issues in blur-my-shell)

**Comment by ryanfelder** [comment]
Sorry for the dupe and thanks for the super helpful response anyway!

**Comment by ryanfelder** [comment]
For anyone looking to accomplish this without a full scale gnome-shell fork, I was able to accomplish it in the following way...

Blur-My-Shell, applications, enable
Customize properties, opacity 255
Whitelist org.gnome.Nautilus

![Screenshot from 2023-11-09 12-05-00](https://github.com/aunetx/blur-my-shell/assets/7475484/bea723ac-5b88-4c5d-9eaa-aea1b6046065)

Then add the following to your .config/gtk-4.0/gtk.css , but you will need to tweak the colors to match your theme. Mine is very brown.

`
.nautilus-window,
.nautilus-window > * > * > * > * > *,
.nautilus-window > * > * > * > * > * > * {
    background-color: rgba(44,35,21,0);
}

.sidebar-pane {
background-color: rgba(44,35,21,.4);
}

.content-pane {
background-color: rgba(34,25,11,1);
}
`

Log out and back in to make it take effect.

![Screenshot from 2023-11-09 12-06-05](https://github.com/aunetx/blur-my-shell/assets/7475484/170b8a91-5e70-4a80-901e-65475fd351d4)

Unfortunately, this means I can only blur applications that can be made transparent via gtk.css, as it requires opacity to be 255. Otherwise my entire Nautilus window goes transparent and that's not my preference.

**Comment by aunetx** [comment]
@ryanfelder I will add (later, when I have time... so that may be as well in 1 month or in 2 years) the possibility to selectively choose the opacity of the selected blurred applications; so that you will be able to both change the gtk theme for some apps; and just blur the background for other ones :)
