### ISSUE TITLE
Windows in secondary monitor flicker when changing workspace

### ISSUE THREAD

**Issue by mgamigo** [aunetx/blur-my-shell#573]
I found that within the last release, windows in the secondary monitor (while using workspaces only in primary display) flicker when changing workspaces. In the flickering the show the blurred background.

However, when switching workspaces from the overview everything works as intended. I am currently using the default settings of blur-my-shell.

**Comment by JockeTF** [comment]
I have the same issue. It can be worked around by disabling background blur for the overview. This mostly defeats the purpose of Blur My Shell though!

**Comment by gaussandhisgun** [comment]
the flicker is caused by the blur effect which seems to be present whenever multiple workspaces are on screen - say, when scrolling workspaces with gestures. this does not happen if gnome is set to have workspaces on all displays, but i use it with workspaces on primary display only, and i am not the only one.

this is what it looks like:

![изображение](https://github.com/aunetx/blur-my-shell/assets/63512006/fd85bc49-3645-4a82-b4a6-339129271109)

on a related note, this blurry background when switching does not apply the pipeline presets, i have mine set up to somewhat mimic the frosted glass effect from windows 10 and the blurred background between workspaces seemingly uses the default gaussian blur
![изображение](https://github.com/aunetx/blur-my-shell/assets/63512006/f6d02345-ee02-40a2-862e-967b34436e9a)

**Comment by aunetx** [comment]
Hello, could you try running blur-my-shell from the latest commit in `master` branch? I should have fixed this, although I am not entirely sure (I could not test it on multiple monitors)

**Comment by JockeTF** [comment]
Thank you, @aunetx! The latest commit appears to have fixed the issue.

**Comment by gaussandhisgun** [comment]
just for future testing reasons, Gnome has a way to use an RDP client (say, an android phone, an iPad or a windows laptop) as a second monitor. sure, it would have some delay, but good enough for just checking out how things work, amirite

**Comment by mgamigo** [comment]
Thanks! When will the "official" extension in the "extension manager" be updated?

Thanks again!

**Comment by aunetx** [comment]
I will try to upload it today or tomorrow, but I'm working on other changes so I first need to reset my working version to upstream :)
