### ISSUE TITLE
Dash flickers when hitting <kbd>Super</kbd>

### ISSUE THREAD

**Issue by BjoernDaase** [aunetx/blur-my-shell#6]
* Fedora 33
* Gnome-shell 3.38.1
* Blur-my-shell 2

When hitting <kbd>Super</kbd> the dash flickers during the transition. The same happens when closing the overview again.

**Comment by aunetx** [comment]
I'm aware of this, this is due to a bug in the `opacity` field of the overview's background element :(

When we put a value different than 1, the overview flickers a lot. And unfortunately, I rely on this field to do "smooth" transitions easily, so it flickers a lot when doing the transition...

I will try to either change the way the transition is done so I don't include the `opacity` in it (although that's a shame I can't rely on the field designed for it), or try to fix it more properly (but I currently have no idea how!)

Thanks for the report anyway, I will try to focus on this :)
