### ISSUE TITLE
Feature request: allow increasing brightness instead of just dimming

### ISSUE THREAD

**Issue by genericusername3** [aunetx/blur-my-shell#88]
Since it would play nicer with some themes, I think that being able to increase the brightness of the effect beyond 1 (up to 2) would be handy. Doing so would make the affected parts more white instead of more black.

**Comment by aunetx** [comment]
I would love to do that, unfortunately I absolutely can't!

I'm using the integrated `Shell.BlurEffect`, and it contains the brightness effect; I can't use it with a number bigger than 1.0 unfortunately.

I will keep this issue open, as I might find another effect to increase brightness, but I'm not sure about it and I would be hard to add, maybe... Will see this!

**Comment by aunetx** [comment]
As I will not be able to do this without increasing complexity by a lot in the extension, I will simply try to solve #50, which will incidentally solve this issue (as you will then be able to increase your wallpaper brightness in krita/the gimp, and use it for the extension).

This is not a perfect fix (because it will prevent the extension from being dynamic), but this is the best I can do...
