### ISSUE TITLE
Blur my Shell and Dash to Panel incompatibilities 

### ISSUE THREAD

**Issue by 31j** [aunetx/blur-my-shell#96]
Dash to Panel version 43
Blur my Shell version 14
(All other extensions disabled, issues do not persist when Dash to Panel is used in isolation or with any of my other extensions outside of Blur my shell)

If dash to panel is moved to the left or right side of the screen (instead of default bottom, or the top) it becomes impossible to interact with all applications let alone see them, only solution is to drop to console, disable all extensions, and reboot. This was all performed in the wayland session of gnome, Fedora 34, Gnome shell 40.2.

I'm not entirely sure what other information I can provide, I tried to record a screen cast as well as record via OBS but both are not successfully saved while the issue is present. I can only record and save if the panel is not moved OR blur my shell is disabled when the panel is moved. 

I'm also not entirely sure what can be done here to fix the issue or if it's a Dash to panel issue, at the very least if the issue is reproducible on other installations with gnome 40 + dash to panel & blur my shell it could help to mention on the main page that the panel must be kept on the top or bottom to avoid creating a situation that requires a user to drop to console.

**Comment by 31j** [comment]
Attached are screenshots depicting what it looks like before moving, the settings window where change is made, as well as what it looks like after. Note, after moving the panel I had the extensions app open and files, they are in the workspace that is currently displayed 

![Screenshot from 2021-06-22 14-57-16](https://user-images.githubusercontent.com/32624322/122984029-19671400-d38c-11eb-83cd-da6ef9b1195e.png)
![Screenshot from 2021-06-22 14-58-03](https://user-images.githubusercontent.com/32624322/122984031-19ffaa80-d38c-11eb-978f-fcf81c026899.png)
![Screenshot from 2021-06-22 14-58-32](https://user-images.githubusercontent.com/32624322/122984032-19ffaa80-d38c-11eb-82f2-5a3987380d86.png)

**Comment by aunetx** [comment]
Thanks for the issue, I think I understand what is going on (although idk why OBS does not want to record, it might be another bug...)

TBH, I did not test dash-to-panel when set to vertical, so it is normal that it breaks at a moment; and I guess that it is just that the panel blur takes up all the vertical space then, just like when it is horizontal.

I will try to fix this quickly, and after this to create a real class that supports dash to panel, instead of the quick fixes I do from time to time (because for the moment, dash to panel blur is implemented in the same way as the normal panel blur is, so it is why it does not support vertical, multi-monitor, etc... normally)

**Comment by aunetx** [comment]
This should be fixed in last commits, I will push soon to extensions.gnome.org!
I also fixed support for static blur for dash-to-panel, so everything should be working fine now
